# Base image
FROM ubuntu:18.04

# Information
LABEL maintainer="Fall-man <a-takeuchi@trinome-design.com>"

# Install package

RUN apt-get update && apt-get install -y \
    build-essential \
    binutils \
    nasm \
    gdb \
    vim \
    man \
    manpages-dev \
    strace